### ISSUE TITLE
Create PDF via tagged release

### ISSUE THREAD

**Issue by hofnerb** [hofnerb/RR_Guideline#2]
@fabian-s, you can create a PDF automatically via Travis-CI by adding a tag. See [Create and Push Tags](https://gist.github.com/hofnerb/68d14f71aef8d01634d9). By this you do not need to upload binaries to the repository.

**Comment by fabian-s** [comment]
meh. travis's pdflatex doesn't get the references right.

**Comment by fabian-s** [comment]
closed in https://github.com/hofnerb/RR_Guideline/commit/a17ad12ef484b23ae0f2fb8cdbd8f0c9781617f5
